### PR TITLE
another bunch of mini optimisations

### PR DESCRIPTION
**Pull request by ghost**
!! Please don't accept my last 2 commits "Create ti83plus.inc" & "Update forth.asm" !!
I've just noticed a problem : the FORTH.8XP then created is not good at all (I tested it on TI84+ & TI83+ : typing Asm(FORTH always gives  a blank screen then reset)
Perhaps your ti83plus.inc version would be ok ?

### CODE REVIEW

**Comment by ghost** [comment]
!! Please don't accept my last 2 commits "Create ti83plus.inc" & "Update forth.asm" !!
I've just noticed a problem : the FORTH.8XP then created is not good at all (I tested it on TI84+ & TI83+ : typing Asm(FORTH always gives  a blank screen then reset)
Perhaps your ti83plus.inc version would be ok ?

**Comment by siraben** [comment]
What assembler are you using?  I'm using `spasm-ng`, where `b_call` does not need the leading paren as well.

**Comment by siraben** [comment]
Ah never mind, read your commit message and it's `spasm-ng` as well.  Just confirmed that one of the words is causing a breaking change, will check in detail tomorrow which one.  Thanks for the optimizations that reduce cycle counts!  Clever use of (ex (sp) hl) too!

**Comment by ghost** [comment]
Thanks !
As I'm using github through a browser online, my actions are too narrowed.
So I decided to close this PR in order to redo it again , this time in a more proper way.
I'v taken screenshot of all optimisations : now I'm rewrite the new PR ;)

**Pull request closed without merging**
